---
name: shybazzite
# description will be included in the image's metadata
description: This is my personal OS image for gaming.

base-image: ghcr.io/ublue-os/bazzite
image-version: stable-43 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install: 
          - org.mozilla.firefox
          - com.valvesoftware.Steam
      - scope: user

  - type: signing
