---
name: shybazzite
description: This is my personal OS image for gaming.

base-image: ghcr.io/ublue-os/bazzite-deck
image-version: stable-43 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - zfs_install.sh

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - atuin

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install: 
          - com.valvesoftware.Steam

  - type: signing
