# Kudos! https://github.com/nhubaotruong/nhubaotruong-ublue/blob/bb53312f28f54c7a75a54349394937065e7c4cc1/containerfiles/zfs-rpms/Containerfile

RUN --mount=type=bind,from=ghcr.io/ublue-os/akmods-zfs:coreos-testing-41,source=/rpms,target=/tmp/akmods-zfs \
    && rpm-ostree override remove zfs-fuse --install /tmp/akmods-zfs/kmods/zfs/zfs-2.2.7-1.fc41.x86_64.rpm \
    && rpm-ostree install /tmp/akmods-zfs/kmods/*.rpm \
    && ostree container commit
