# This stage is responsible for holding onto
# your config without copying it directly into
# the final image
# Copy modules
# The default modules are inside blue-build/modules
# Custom modules overwrite defaults
FROM scratch AS stage-modules
COPY --from=ghcr.io/blue-build/modules:latest /modules /modules
# Bins to install
# These are basic tools that are added to all images.
# Generally used for the build process. We use a multi
# stage process so that adding the bins into the image
# can be added to the ostree commits.
FROM scratch AS stage-bins
COPY --from=gcr.io/projectsigstore/cosign /ko-app/cosign /bins/cosign
COPY --from=docker.io/mikefarah/yq /usr/bin/yq /bins/yq
COPY --from=ghcr.io/blue-build/cli:latest-installer /out/bluebuild /bins/bluebuild

# Keys for pre-verified images
# Used to copy the keys into the final image
# and perform an ostree commit.
#
# Currently only holds the current image's
# public key.
FROM scratch AS stage-keys

# Main image
FROM ghcr.io/ublue-os/bazzite:stable AS shybazzite
ARG RECIPE=recipe.yml
ARG IMAGE_REGISTRY=localhost
ARG MODULE_DIRECTORY="/tmp/modules"
ARG IMAGE_NAME="shybazzite"
ARG BASE_IMAGE="ghcr.io/ublue-os/bazzite"
ARG FORCE_COLOR=1
ARG CLICOLOR_FORCE=1
ARG RUST_LOG_STYLE=always
# Key RUN
RUN --mount=type=bind,from=stage-keys,src=/keys,dst=/tmp/keys \
  mkdir -p /etc/pki/containers/ \
  mkdir -p /usr/etc/pki/containers/ \
  && cp /tmp/keys/* /etc/pki/containers/ \
  && cp /tmp/keys/* /usr/etc/pki/containers/ \
  && ostree container commit

# Bin RUN
RUN --mount=type=bind,from=stage-bins,src=/bins,dst=/tmp/bins \
  mkdir -p /usr/bin/ \
  && cp /tmp/bins/* /usr/bin/ \
  && ostree container commit

# Module RUNs
RUN \
--mount=type=bind,from=stage-modules,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,from=ghcr.io/blue-build/cli:v0.8.20-build-scripts,src=/scripts/,dst=/tmp/scripts/ \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-shybazzite-stable,sharing=locked \
  /tmp/scripts/run_module.sh 'files' '{"type":"files","files":[{"../../../common/files/usr":"/usr"},{"../../../common/files/etc":"/etc"}]}' \
  && ostree container commit
# Kudos! https://github.com/nhubaotruong/nhubaotruong-ublue/blob/bb53312f28f54c7a75a54349394937065e7c4cc1/containerfiles/zfs-rpms/Containerfile

RUN --mount=type=bind,from=ghcr.io/ublue-os/akmods-zfs:coreos-stable-40,source=/rpms,target=/tmp/akmods-zfs \
    rpm-ostree cliwrap install-to-root / && \
    rpm-ostree install pv /tmp/akmods-zfs/kmods/zfs/*.rpm && \
    ostree container commit

RUN \
--mount=type=bind,from=stage-modules,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,from=ghcr.io/blue-build/cli:v0.8.20-build-scripts,src=/scripts/,dst=/tmp/scripts/ \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-shybazzite-stable,sharing=locked \
  /tmp/scripts/run_module.sh 'rpm-ostree' '{"type":"rpm-ostree","repos":["https://pkgs.tailscale.com/stable/fedora/tailscale.repo"],"install":["code","zerotier-one","tailscale","firefox"]}' \
  && ostree container commit
RUN \
--mount=type=bind,from=stage-modules,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,from=ghcr.io/blue-build/cli:v0.8.20-build-scripts,src=/scripts/,dst=/tmp/scripts/ \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-shybazzite-stable,sharing=locked \
  /tmp/scripts/run_module.sh 'default-flatpaks' '{"type":"default-flatpaks","system":{"remove":["org.gnome.eog"]}}' \
  && ostree container commit
RUN \
--mount=type=bind,from=stage-modules,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,from=ghcr.io/blue-build/cli:v0.8.20-build-scripts,src=/scripts/,dst=/tmp/scripts/ \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-shybazzite-stable,sharing=locked \
  /tmp/scripts/run_module.sh 'bling' '{"type":"bling","install":["ublue-update","1password","dconf-update-service"]}' \
  && ostree container commit
RUN \
--mount=type=bind,from=stage-modules,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,from=ghcr.io/blue-build/cli:v0.8.20-build-scripts,src=/scripts/,dst=/tmp/scripts/ \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-shybazzite-stable,sharing=locked \
  /tmp/scripts/run_module.sh 'fonts' '{"type":"fonts","fonts":{"nerd-fonts":["FiraCode","CascadiaCode","Hack","SourceCodePro","Terminus","JetBrainsMono","NerdFontsSymbolsOnly"],"google-fonts":["Roboto","Open Sans"]}}' \
  && ostree container commit
RUN \
--mount=type=bind,from=stage-modules,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,from=ghcr.io/blue-build/cli:v0.8.20-build-scripts,src=/scripts/,dst=/tmp/scripts/ \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-shybazzite-stable,sharing=locked \
  /tmp/scripts/run_module.sh 'signing' '{"type":"signing"}' \
  && ostree container commit

RUN --mount=type=bind,from=ghcr.io/blue-build/cli:v0.8.20-build-scripts,src=/scripts/,dst=/scripts/ \
  /scripts/post_build.sh

# Labels are added last since they cause cache misses with buildah
LABEL org.blue-build.build-id="265c05fc-fc35-44c5-9d39-8b6900d9bb68"
LABEL org.opencontainers.image.title="shybazzite"
LABEL org.opencontainers.image.description="This is my personal OS image for my gaming workstation"
LABEL org.opencontainers.image.source=""
LABEL io.artifacthub.package.readme-url=https://raw.githubusercontent.com/blue-build/cli/main/README.md