name: shybazzite
alt-tags: [ handheld ]
description: This is my personal OS image for my handheld gaming devices.
base-image: ghcr.io/ublue-os/bazzite-deck
image-version: 40
modules:
  - from-file: ../../../common/common-zfs.yml
  - type: files
    files:
      - source: files
        destination: /
  - type: default-flatpaks
    system:
      remove:
        - org.gnome.eog
  - type: bling
    install:
      - ublue-update
      - 1password
      - dconf-update-service
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - CascadiaCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
  - type: signing
