---
name: build-ublue-custom
on:
  schedule:
    - cron: '0 6 * * 5'  # 0600 hours [UTC], every Sat.
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build and push custom Bazzite image for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - "desktop"
          - "handheld"
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.6.2
        with:
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_username: ${{ github.repository_owner }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: ./images/${{ matrix.target }}
  build-iso:
    name: Build and upload custom Bazzite ISO to R2 (private) ${{ matrix.target }}
    needs: [build-and-push]
    strategy:
      fail-fast: false
      matrix:
        target:
          - "desktop"
          - "handheld"
    if: ${{ (github.event_name == 'schedule' && needs.build-and-push.result == 'success') || (github.event_name == 'workflow_dispatch' && needs.build-and-push.result == 'success') }}
    runs-on:  ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build ISOs
        uses: jasonn3/build-container-installer@v1.2.2
        id: build
        with:
          arch: x86_64
          image_name: shybazzite
          image_repo: ghcr.io/shymega
          version: 40
          image_tag: ${{ matrix.target }}-40
          secure_boot_key_url: 'https://github.com/ublue-os/bazzite/raw/main/secure_boot.der'
          enrollment_password: 'universalblue'
          iso_name: shybazzite-${{ matrix.target }}.iso
          enable_cache_dnf: "true"
          enable_cache_skopeo: "true"
          enable_flatpak_dependencies: "false"

      - name: Move ISOs to Upload Directory
        id: upload-directory
        shell: bash
        run: |
          ISO_UPLOAD_DIR=${{ github.workspace }}/upload
          mkdir ${ISO_UPLOAD_DIR}
          mv ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }} ${ISO_UPLOAD_DIR}
          mv ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}-CHECKSUM ${ISO_UPLOAD_DIR}
          echo "iso-upload-dir=${ISO_UPLOAD_DIR}" >> $GITHUB_OUTPUT

      - name: Upload ISOs and Checksum to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shybazzite-${{ matrix.target }}
          path: ${{ steps.upload-directory.outputs.iso-upload-dir }}
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
